services:
    app:
      build: .
      image: watersheds:latest
      environment:
        - FLASK_APP=app.py
        - FLASK_DEBUG=True
        - PYTHONUNBUFFERED=1
      container_name: watersheds
      command: flask --app app --debug run --host=0.0.0.0 --port 5000
      ports:
        - "8047:5000"
